name = "ducksearch"
type = "javascript"
account_id = ""
workers_dev = true
kv_namespaces = [
  { binding = "CHANNEL_NSFW_CACHE", id = "" }
]

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[env.development]
vars = { COMMANDS_DEV_GUILD = "" }
kv_namespaces = [
  { binding = "CHANNEL_NSFW_CACHE", id = "" }
]
